// <auto-generated/>
using EUC.Profile.Buddy.Common.Profile;
using EUC.Profile.Buddy.Common.User;

namespace EUC.Profile.Buddy.CLI
{

    public class Program
    {
        public static async Task Main(string[] args)
        {
            IUserDetail user = new UserDetail();
            await Console.Out.WriteLineAsync($"User Name: {user.UserName}");
            await Console.Out.WriteLineAsync($"Profile Directory: {user.ProfileDirectory}");
            if (args.Length > 0)
            {
                var command = args[0];

                switch (command)
                {
                    case "ClearTemp":
                        await Console.Out.WriteLineAsync("Clearing Temp Data");
                        IProfile profile = new EUC.Profile.Buddy.Common.Profile.Profile();
                        profile.ExecuteAction("Clear Temporary Data", user.ProfileDirectory);
                        break;
                }
            }
            
        }
    }
}