// <auto-generated/>
using EUC.Profile.Buddy.Common.Profile;
using EUC.Profile.Buddy.Common.User;

namespace EUC.Profile.Buddy.CLI
{

    public class Program
    {
        public static async Task Main(string[] args)
        {
            IUserDetail user = new UserDetail();
            await Console.Out.WriteLineAsync($"User Name: {user.UserName}");
            await Console.Out.WriteLineAsync($"Profile Directory: {user.ProfileDirectory}");

            
        }
    }
}