// <auto-generated/>
using EUC.Profile.Buddy.Common.Profile;
using EUC.Profile.Buddy.Common.User;

namespace EUC.Profile.Buddy.CLI
{

    public class Program
    {
        public static async Task Main(string[] args)
        {
            await Console.Out.WriteLineAsync("Coming soon...");
        }
    }
}