// <auto-generated/>
using EUC.Profile.Buddy.GUI.Classes;

namespace EUC.Profile.Buddy.GUI.Forms
{
    public partial class FormDetail : Form
    {
        private string userProfileType;
        private string userName;
        private string profileDirectory;

        public FormDetail(string userProfileType, string userName, string profileDirectory)
        {
            InitializeComponent();
            this.userProfileType = userProfileType;
            this.userName = userName;
            this.profileDirectory = profileDirectory;
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void FormDetail_Load(object sender, EventArgs e)
        {
            this.Location = new Point(((Screen.PrimaryScreen.WorkingArea.Width - this.Width) - FormMain.ActiveForm.Width) - 3, (Screen.PrimaryScreen.WorkingArea.Height - this.Height));
            GUIElements.UpdateLabel(this.lblProfileDetail, $"Profile Detail for {this.userName} ({this.profileDirectory})");
            GUIElements.UpdateProfileDetailDataGrid(this.userProfileType, this.dgProfileDetails);
            GUIElements.UpdateFolderRedirectionDataGrid(this.dgFolderRedirection);
            GUIElements.SizeDataGrid(this.dgProfileDetails);
            GUIElements.SizeDataGrid(this.dgFolderRedirection);
        }

        private void btnProfileDetailsSort_Click(object sender, EventArgs e)
        {
            GUIElements.SortDataGrid(this.dgProfileDetails, this.btnProfileDetailsSort);
        }

        private void btnFolderRedirectionSort_Click(object sender, EventArgs e)
        {
            GUIElements.SortDataGrid(this.dgFolderRedirection, this.btnFolderRedirectionSort);
        }
    }
}
